# MASKS
DISABLED = 0
ENABLED  = 1
MASK_PORT = 0x1FF
MASK_PKT_ID = 0xFF
MASK_IPV4_TLEN = 0xFFFF
MASK_LOCAL_VAR = 0xFF
MASK_FLAG = 0x1
MASK_FLOW = 0xFF

# PKT Filter Values
PKT_FILTER_DEFAULT = 0
PKT_FILTER_ALL     = 1

# Flow Next Instruction Values
INSTRUCTION_FINISH = 0

#Registers Modes
REG_OP_MODE_DISABLED  = 0
REG_OP_MODE_GET       = 1
REG_OP_MODE_PUT       = 2
REG_OP_MODE_DECREMENT = 3
REG_OP_MODE_INCREMENT = 4

# Mirror 
MIRROR_DIR_INGRESS = "INGRESS"
MIRROR_DIR_EGRESS = "EGRESS"

MIRROR_TYPE_I2E = 1
MIRROR_TYPE_E2E = 2

PKT_TYPE_NORMAL = 1
PKT_TYPE_MIRROR = 2


# Ipv4 Protocols
PROTO_ICMP      = 1
PROTO_TCP       = 6
PROTO_UDP       = 17
PROTO_GEN       = 200

MASK_PROTO      = 0xFF

MASK_IPV4_SRC_ADDR = 0xFFFFFFFF
MASK_IPV4_DST_ADDR = 0xFFFFFFFF
####### Instructions #######

# I_COND
COND_MODE_EQUALS      = 1
COND_MODE_GREATER     = 2
COND_MODE_LESS        = 3
COND_MODE_NOT_EQUALS  = 4

COND_ACTION_DROP      = 1
COND_ACTION_EXEC      = 2

# I_PAD

MODE_PAD        = 0
MODE_PADTO      = 1
MODE_PADTTERN   = 2
MODE_VAR        = 3

SHARED_META_SIZE = 13

MASK_POS_FILTER_IPV4_PROTO = 0x00ff

MASK_COND_MODE = 0xF
MASK_COND_VAL = 0xFFFFFFFF
MASK_COND_VAL_MOST_SIGNIFICANT_BIT = 0x80000000
####### Header Phase #######
HEADER_IPV4_TTL = 1
HEADER_IPV4_DST = 2
HEADER_TCP_ACK_NO = 3
HEADER_TCP_SEQ_NO = 4
HEADER_TCP_FLAGS  = 5
HEADER_IPV4_IDENTIFICATION  = 6
HEADER_IPV4_SRC = 7


MASK_TCP_NS_FLAG =  0x100  #  8  ECN-nonce concealment protection 
MASK_TCP_CWR_FLAG =  0x80  #  7  Congestion Window Reduced 
MASK_TCP_ECE_FLAG =  0x40  #  6  ECN-Echo: Congestion 
MASK_TCP_URG_FLAG =  0x20  #  5  Urgent pointer field is 
MASK_TCP_ACK_FLAG =  0x10  #  4  Acknowledgment field is 
MASK_TCP_PSH_FLAG =  0x08  #  3  Push Function: request immediate data 
MASK_TCP_RST_FLAG =  0x04  #  2  Reset the connections
MASK_TCP_SYN_FLAG =  0x02  #  1  Synchronize sequence numbers (used to 
MASK_TCP_FIN_FLAG =  0x01  #  0  Finish sending data

MASK_TCP_SPORT = 0xFFFF
MASK_TCP_DPORT = 0xFFFF
MASK_UDP_SPORT = 0xFFFF
MASK_UDP_DPORT = 0xFFFF

MASK_PROGRAM_ID = 0xFF
####### PORT CONFIGS #######

PORT_SPEED_10G = "BF_SPEED_10G"
PORT_SPEED_25G = "BF_SPEED_25G"
PORT_SPEED_40G = "BF_SPEED_40G"
PORT_SPEED_50G = "BF_SPEED_50G"
PORT_SPEED_100G = "BF_SPEED_100G"

PORT_SPEED_BF = {100: PORT_SPEED_100G, 
                 50: PORT_SPEED_50G,
                 40: PORT_SPEED_40G,
                 25: PORT_SPEED_25G,
                 10: PORT_SPEED_10G,
                 }

FEC_NONE = "BF_FEC_TYP_NONE"
# FEC_FEC = "BF_FEC_TYP_FC"
FEC_RS = "BF_FEC_TYP_RS"

LOOPBACK_NONE = "BF_LPBK_NONE"
LOOPBACK_MAC_NEAR = "BF_LPBK_MAC_NEAR"
# LOOPBACK_MAC_FAR = "BF_LPBK_MAC_FAR"
# LOOPBACK_PCS_NEAR = "BF_LPBK_PCS_NEAR"
# LOOPBACK_SERDES_NEAR = "BF_LPBK_SERDES_NEAR"
# LOOPBACK_SERDES_FAR = "BF_LPBK_SERDES_FAR"

PORT_LOOPBACK_BF = {
                True: LOOPBACK_MAC_NEAR, 
                False: LOOPBACK_NONE,
                 }
PORT_FEC_BF = {
                (PORT_SPEED_100G, LOOPBACK_NONE): FEC_RS, 
            }

#SWITCHES MODELS
TOFINO_1 = 'Tofino1'
TOFINO_2 = 'Tofino2'

#Arch 
TF1 = "tf1"
TF2 = "tf2"

#HASH KEYS

HASH_ETH_SRC_ADDR = 'eth_src_addr'
HASH_IPV4_SRC_ADDR = 'ipv4_src_addr'
HASH_IPV4_DST_ADDR = 'ipv4_dst_addr'
HASH_IPV4_PROTO = 'ipv4_protocol'
HASH_L4_SPORT = 'l4_src_port'
HASH_L4_DPORT = 'l4_dst_port'
HASH_FIELD1 = 'field1'

FINAL_STAGE = 10

# Timestamps for 16ns accuracy
# TIMESTAMP_1S = 	0x03B9ACA0
# TIMESTAMP_2S = 	0x07735940
# TIMESTAMP_3S = 	0x0B2D05E0
# TIMESTAMP_4S = 	0x0EE6B280
# TIMESTAMP_5S = 	0x12905F20
# TIMESTAMP_10S = 0x254F5E10
# TIMESTAMP_20S = 0x4A9EBC20
# TIMESTAMP_30S = 0x6FEE1A30
# TIMESTAMP_40S = 0x954D7840
# TIMESTAMP_60S = 0xDF9EAC60

# Timestamp for global_tstamp[47:16] accuracy
TIMESTAMP_1S = 0x3B9A
TIMESTAMP_2S = 0x7735
TIMESTAMP_3S = 0xB2D0
TIMESTAMP_4S = 0xEE6B
TIMESTAMP_5S = 0x12A05
TIMESTAMP_10S = 0x2540B
TIMESTAMP_20S = 0x4A817
TIMESTAMP_30S = 0x6FC23
TIMESTAMP_40S = 0x9502F
TIMESTAMP_60S = 0xDF847










